
import datetime
import json
import logging
import argparse

from etc import logger_config, constants
from modules import meta_file


#################################################################
# Parser settings
#################################################################

parser = argparse.ArgumentParser(
  prog='Deployment tool',
  description='Find detailed description in README.md'
)

parser.add_argument('-w', '--workflow', help='Name of the workflow to use for the deplyoment, defined in ./etc/workflow.json', required=True)
parser.add_argument('-o', '--object_file_list', help='Object file list (generated by GNU make)', required=True)

args = parser.parse_args()

#################################################################

logging.debug(f"{args.workflow=}, {args.object_file_list}")

meta_file = meta_file.Meta_File(workflow_name=args.workflow)
meta_file.import_objects_from_config_file(args.object_file_list)
meta_file.write_meta_file()

