#!/bin/bash

FILE=/QOpenSys/run/warehouse.sock

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
#SCRIPT_DIR=$SCRIPT_DIR/warehouse

PID=$SCRIPT_DIR/etc/warehouse.pid
LOG_FILE=$SCRIPT_DIR/log/warehouse
LOG_LEVEL='debug'
PROCESS_COUNT=3
SOCKET_FILE=/QOpenSys/run/warehouse.sock


#START_CMD=$SCRIPT_DIR/venv/bin/python $SCRIPT_DIR/venv/bin/gunicorn --reload -p $PID --log-file $LOG_FILE --log-level $LOG_LEVEL --workers $PROCESS_COUNT --bind unix:$SOCKET_FILE wsgi:app &
START_CMD=$SCRIPT_DIR/venv/bin/python $SCRIPT_DIR/venv/bin/gunicorn --reload -p $PID --log-file $LOG_FILE --log-level $LOG_LEVEL --workers $PROCESS_COUNT --bind :7000 wsgi:app &
# START_CMD=$SCRIPT_DIR/venv/bin/gunicorn -b :7000  warehouse.wsgi
# START_CMD=$SCRIPT_DIR/venv/bin/python $SCRIPT_DIR/venv/bin/gunicorn --workers 3 --bind unix:/QOpenSys/run/warehouse.sock wsgi:app &


start() {
    if [ -S /QOpenSys/run/warehouse.sock ]; then
        echo "Process already exist"
        echo "1. Check if process is running:"
        echo "    ps -ef | grep warehouse"
        echo "2. If no precess is running check if socket file exists and remove it:"
        echo "    rm $SOCKET_FILE"

    else
        echo "Activate virtual environment: $SCRIPT_DIR/venv/bin/activate"

        source $SCRIPT_DIR/venv/bin/activate
        echo "Start service"
        $START_CMD
    fi
}

stop() {
    kill `cat $PID`
    rm $PID
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       # code to check status of app comes here 
       # example: status program_name
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac
